# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0" # indicate our selected version of Xcode

    steps:
      - checkout
      # restore pods related caches
      - restore_cache:
          keys:
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}
            - cocoapods-cache-v1
      # update CocoaPods
      - run: make setup

      # build project
      - run: make build

      # save pods related files
      - save_cache:
          key: cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
          paths:
            - build/xcode/Pods
            - ~/.cocoapods

  test:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      # restore pods related caches
      - restore_cache:
          keys:
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}
            - cocoapods-cache-v1

      # update CocoaPods
      - run: make setup

      # build project
      - run: make test

      # save pods related files
      - save_cache:
          key: cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
          paths:
            - build/xcode/Pods
            - ~/.cocoapods
