# iOS CircleCI 2.0 configuration file
workflows:
  version: 2
  setup-build--test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - setup

version: 2
jobs:
  setup:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0" # indicate our selected version of Xcode

    steps:
      - checkout

      # make a workspace directory
      - run: mkdir -p ci-workspace

      # restore pods related caches
      - restore_cache:
          keys:
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}
            - cocoapods-cache-v1

      # update CocoaPods
      - run: make setup

      # save pods related files
      - save_cache:
          key: cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
          paths:
            - build/xcode/Pods
            - ~/.cocoapods

      # persist settings to the workspace
      - persist_to_workspace:
          root: ci-workspace
          paths:
            - echo-output

  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0" # indicate our selected version of Xcode

    steps:
      - checkout

      # attach the workspace from the setup job
      - attach_workspace:
          at: ci-workspace

  test:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      # attach the workspace from the setup job
      - attach_workspace:
          at: ci-workspace

      # build project
      - run: make test
