# iOS CircleCI 2.0 configuration file
workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build

version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: "10.0.0" # indicate our selected version of Xcode

    steps:
      - checkout

      # make a workspace directory
      - run: mkdir -p ci-workspace

      # restore pods related caches
      - restore_cache:
          keys:
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}
            - cocoapods-cache-v1

      # update CocoaPods
      - run: make setup

      # build project
      - run: make build

      # save pods related files
      - save_cache:
          key: cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "build/xcode/Podfile.lock" }}
          paths:
            - build/xcode/Pods
            - ~/.cocoapods

      # persist settings to the workspace
      - persist_to_workspace:
        root: ci-workspace
        paths:
          - echo-output

  test:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      # attach the workspace from the build job
      - attach_workspace:
        at: ci-workspace

      # build project
      - run: make test
